name: cartracker
version: "1.0"
config-version: 2

profile: cartracker

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  cartracker:
    +materialized: view
