from processing.processors.parse_detail_page import parse_cars_detail_page_html_v1
from processing.processors.results_page_cards import parse_cars_results_page_html_v3

__all__ = ["parse_cars_detail_page_html_v1", "parse_cars_results_page_html_v3"]
