version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: srp_observations
      - name: artifact_processing
      - name: raw_artifacts
      - name: detail_observations
      - name: detail_carousel_hints
      - name: runs
      - name: search_configs