apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram-primary
        type: telegram
        settings:
          bottoken: ${TELEGRAM_API}
          chatid: ${TELEGRAM_CHAT_ID}
          parseMode: HTML
        disableResolveMessage: false
